package game.desktop;

import java.io.FileNotFoundException;
import java.io.IOException;

import com.badlogic.gdx.Files.FileType;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;

import game.Core;

/**
 * The DesktopLauncher class initialises the game window variables (sizes) and
 * uses the ConfigLoader class to load additional data.
 * 
 * @author Automatically generated by the LibGDX library
 */

public class DesktopLauncher {
  /**
   * The main method initialises configuration data and starts the application
   * with a new instance of a game Core object.
   * 
   * @param arg Start-up arguements.
   * @throws FileNotFoundException If the config file does not exist.
   * @throws IOException           If the config file cannot be read.
   */

  public static void main(String[] arg) throws FileNotFoundException, IOException {
    LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();

    ConfigLoader loader = new ConfigLoader();
    loader.loadConfig("config.cfg");

    config.addIcon("icon-256.png", FileType.Internal);
    config.addIcon("icon-64.png", FileType.Internal);
    config.addIcon("icon-32.png", FileType.Internal);

    config.width = Core.width;
    config.height = Core.height;
    config.title = Core.TITLE;
    config.resizable = false;

    new LwjglApplication(new Core(), config);
  }

}
